name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-24.04 ]
        build_type: [ Debug, Release ]
        cxx_compiler: [ g++-14 ]
        include:
          - os: ubuntu-24.04
            build_type: Debug
            sanitizers: -fsanitize=address,undefined
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'oracle'

      - name: Setup build dependencies
        run: |
          sudo apt update
          sudo add-apt-repository universe
          sudo apt install gcc-14 libzip-dev zipcmp zipmerge ziptool ninja-build llvm
          sudo ln -s /usr/lib/llvm-18/bin/FileCheck /usr/bin/FileCheck
          sudo ln -s /usr/lib/llvm-18/bin/split-file /usr/bin/split-file

      - name: Setup Python environment
        run:
          pip install -r requirements.txt

      - name: Configure
        run: >
          cmake --version
          cmake -GNinja -Bbuild -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DCMAKE_CXX_COMPILER=${{ matrix.cxx_compiler }}
          -DCMAKE_CXX_FLAGS=${{ matrix.sanitizers }} -S ${{ github.workspace }}

      - name: Build
        run: |
          cmake --build build

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest --extra-verbose --output-on-failure
